# Generated by Django 5.0.6 on 2024-06-11 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newscard',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='newscard',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newscard',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newscard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
